FROM tiangolo/uwsgi-nginx-flask:python3.7-alpine3.8
RUN apk --update add bash nano
ENV STATIC_URL /static
ENV STATIC_PATH /var/www/app/static


WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY apps/cache-python .
